# This CloudFormation template sets up an ECS Cluster for a Sports API application.
# It includes the following resources:
#
# - ECS Cluster: Creates an ECS cluster named 'sports-api-cluster'.
# - VPC: Creates a new VPC with CIDR block 10.0.0.0/16, DNS support, and DNS hostnames enabled.
# - Subnets: Creates two public subnets in different availability zones within the VPC.
# - Internet Gateway: Creates and attaches an Internet Gateway to the VPC.
# - Route Table: Creates a route table and adds a default route to the Internet Gateway.
# - Security Group: Creates a security group allowing HTTP traffic on port 80.
# - Task Definition: Defines an ECS task with a container running the Sports API.
# - IAM Role: Creates an IAM role for ECS task execution with necessary policies.
# - Application Load Balancer (ALB): Creates an ALB with an associated security group.
# - Target Group: Creates a target group for the ALB with health check configuration.
# - Listener: Creates a listener for the ALB to forward traffic to the target group.
# - ECS Service: Creates an ECS service to run the task definition, with load balancer configuration.
#

AWSTemplateFormatVersion: "2010-09-09"
Description: ECS Cluster for Sports API using Default VPC

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: Select the Default VPC

  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Select at least two subnets from the Default VPC

Resources:
  # Create an ECS Cluster
  SportsApiCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: sports-api-cluster

  # Security Group
  SportsApiSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP traffic
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: 0
          ToPort: 65535
          CidrIp: 0.0.0.0/0

  # Task Definition for Sports API
  SportsApiTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: sports-api-task
      Cpu: "256"
      Memory: "512"
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !GetAtt EcsTaskExecutionRole.Arn
      ContainerDefinitions:
        - Name: sports-api-container
          Image: 449095351082.dkr.ecr.us-east-1.amazonaws.com/sports_api # Replace with your image URI
          PortMappings:
            - ContainerPort: 8080
              Protocol: tcp
              AppProtocol: http
          Environment:
            - Name: NBA_API
              Value: "76ccbdb3040557b11709cd3d4e59a313784a25074d26c3c277d513ba9ad73613" # Replace with actual API key or desired value

  # Create ECS Task Execution Role
  EcsTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}-EcsTaskExecutionRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly

  # Create an Application Load Balancer (ALB)
  SportsApiALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: sports-api-alb
      Scheme: internet-facing
      Subnets: !Ref SubnetIds
      SecurityGroups:
        - !Ref SportsApiSecurityGroup
      Type: application

  # Create a target group for the ALB
  SportsApiTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: Ecs-sports-api-service
      Port: 8080
      Protocol: HTTP
      VpcId: !Ref VpcId
      TargetType: ip
      HealthCheckProtocol: HTTP
      HealthCheckPort: "8080"
      HealthCheckPath: /sports
      HealthCheckIntervalSeconds: 60
      HealthCheckTimeoutSeconds: 10
      HealthyThresholdCount: 3
      UnhealthyThresholdCount: 3

  # Create a listener for the ALB
  SportsApiListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref SportsApiALB
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref SportsApiTargetGroup

  # ECS Service to run the Task Definition
  SportsApiService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: sports-api-service
      Cluster: !Ref SportsApiCluster
      TaskDefinition: !Ref SportsApiTaskDefinition
      DesiredCount: 2
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets: !Ref SubnetIds
          SecurityGroups:
            - !Ref SportsApiSecurityGroup
      LoadBalancers:
        - ContainerName: sports-api-container
          ContainerPort: 8080
          TargetGroupArn: !Ref SportsApiTargetGroup
    DependsOn:
      - SportsApiListener
      - SportsApiALB
      - SportsApiTargetGroup

# Outputs:
# - SportsApiALBDNS: DNS name of the ALB.
# - SportsApiTargetGroupArn: ARN of the target group.
# - SportsApiServiceName: Name of the ECS service.
Outputs:
  SportsApiALBDNS:
    Description: "DNS Name of the Sports API ALB"
    Value: !GetAtt SportsApiALB.DNSName

  SportsApiTargetGroupArn:
    Description: "ARN of the Sports API Target Group"
    Value: !Ref SportsApiTargetGroup

  SportsApiServiceName:
    Description: "Name of the Sports API ECS Service"
    Value: !Ref SportsApiService
